import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  authConfigurationError,
  authServiceError,
} from "@/features/auth/errors";
import { initialAuthActionState } from "@/features/auth/state";

const {
  authenticateWithAccessToken,
  createPendingRegistrationToken,
  registerAccessTokenAccount,
  redirect,
} = vi.hoisted(() => ({
  authenticateWithAccessToken: vi.fn(),
  createPendingRegistrationToken: vi.fn(),
  registerAccessTokenAccount: vi.fn(),
  redirect: vi.fn(),
}));

vi.mock("@/server/supabase/access-token-auth", () => ({
  authenticateWithAccessToken,
  createPendingRegistrationToken,
  registerAccessTokenAccount,
  InvalidAccessTokenError: class InvalidAccessTokenError extends Error {},
  InvalidRegistrationTokenError: class InvalidRegistrationTokenError extends Error {},
}));
vi.mock("@/server/supabase/auth", () => ({ createServerAuthClient: vi.fn() }));
vi.mock("next/navigation", () => ({ redirect }));

import {
  generateRegistrationToken,
  registerWithToken,
  signInWithToken,
} from "@/features/auth/actions";

function formData(values: Record<string, string>) {
  const data = new FormData();
  Object.entries(values).forEach(([name, value]) => data.set(name, value));
  return data;
}

describe("token auth actions", () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  it("returns a token generated by the server before registration", async () => {
    const generatedToken = `pfc_${"a".repeat(64)}`;
    createPendingRegistrationToken.mockResolvedValue(generatedToken);

    await expect(
      generateRegistrationToken(initialAuthActionState, formData({})),
    ).resolves.toEqual({
      generatedToken,
      message: "Сохраните токен: повторно показать его будет невозможно.",
    });
    expect(createPendingRegistrationToken).toHaveBeenCalledOnce();
    expect(registerAccessTokenAccount).not.toHaveBeenCalled();
  });

  it("registers with only the pending token and returns a recovery code", async () => {
    const token = `pfc_${"a".repeat(64)}`;
    const recoveryCode = `pfr_${"b".repeat(64)}`;
    registerAccessTokenAccount.mockResolvedValue(recoveryCode);

    await expect(
      registerWithToken(initialAuthActionState, formData({ token })),
    ).resolves.toEqual({
      registrationComplete: true,
      recoveryCode,
      message:
        "Сохраните токен авторизации и код восстановления. Они показаны только один раз.",
    });
    expect(registerAccessTokenAccount).toHaveBeenCalledWith(token);
  });

  it("maps missing server configuration to a safe message", async () => {
    const configurationError = new Error("secret config is missing");
    configurationError.name = "ZodError";
    createPendingRegistrationToken.mockRejectedValue(configurationError);

    await expect(
      generateRegistrationToken(initialAuthActionState, formData({})),
    ).resolves.toEqual({ message: authConfigurationError });
  });

  it("requires a valid token format before looking up an account", async () => {
    await expect(
      signInWithToken(initialAuthActionState, formData({ token: "invalid" })),
    ).resolves.toMatchObject({ message: "Проверьте введённый токен" });
    expect(authenticateWithAccessToken).not.toHaveBeenCalled();
  });

  it("maps unexpected auth failures without exposing provider details", async () => {
    authenticateWithAccessToken.mockRejectedValue(
      new Error("raw internal failure"),
    );

    await expect(
      signInWithToken(
        initialAuthActionState,
        formData({ token: `pfc_${"a".repeat(64)}` }),
      ),
    ).resolves.toEqual({ message: authServiceError });
  });
});
